sudo: false
language: rust
rust:
  - nightly
  - beta
  - stable

# whitelist
branches:
  only:
    - master

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
cache:
  apt: true
  rust-download: true
  directories:
    - $TRAVIS_BUILD_DIR/target
    - ~/.cargo
notifications:
  email:
    on_success: never