sudo: false
language: rust
cache: cargo
rust:
- stable
- beta
- nightly
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  (cargo install --git https://github.com/rust-lang-nursery/rustfmt || true) &&
  export PATH=$HOME/.local/bin:$PATH &&
  export PATH=$HOME/.cargo/bin:$PATH
script:
- |
  cargo fmt &&
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo bench &&
  travis-cargo --only stable doc
after_success:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis-cargo coveralls --no-sudo --verify; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./kcov/build/src/kcov --verify --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/kontex-*; fi

env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
matrix:
  allow_failures:
    - rust: nightly
    - rust: beta